name: build_ipwnder_libs

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:

  build-iphoneos:
    runs-on: macos-12
    steps:
    - name: envdetails
      run: ls && echo && pwd
    - uses: actions/checkout@v2
    - name: download submodules
      run: git submodule update --init
    - name: modify checkm8_arm64.c
      run: cd ra1npoc/src/exploit && awk -v ln=414 -v code="io_close(client)" 'NR == ln {print code} 1' checkm8_arm64.c > checkm8_arm64.c.new && mv checkm8_arm64.c.new checkm8_arm64.c
    - name: envdetails
      run: ls && echo && ls ra1npoc && pwd
    - name: regrets
      run: mkdir IOKit && cd IOKit && cp -r /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/IOKit.framework/Versions/A/Headers/ .
    - name: trollage
      run: rm -rf IOKit/IOKitLib.h && cp IOKitLib.h IOKit
    - name: build
      run: make
      
    - name: create static libs
      run: chmod +x create_libs && ./create_libs
      
    - name: upload checkm8_arm64.a
      id: upload_checkm8_arm64
      uses: actions/upload-artifact@v2
      with:
        name: "checkm8_arm64.a"
        path: ${{ github.workspace }}/checkm8_arm64.a
        
    - name: upload common.a
      id: upload_common
      uses: actions/upload-artifact@v2
      with:
        name: "common.a"
        path: ${{ github.workspace }}/common.a
        
    - name: upload iousb.a
      id: upload_iousb
      uses: actions/upload-artifact@v2
      with:
        name: "iousb.a"
        path: ${{ github.workspace }}/iousb.a
        
    - name: upload limera1n.a
      id: upload_limera1n
      uses: actions/upload-artifact@v2
      with:
        name: "limera1n.a"
        path: ${{ github.workspace }}/limera1n.a
        
    - name: upload payload.a
      id: upload_payload
      uses: actions/upload-artifact@v2
      with:
        name: "payload.a"
        path: ${{ github.workspace }}/payload.a

    - name: upload s5l8950x.a
      id: upload_s5l8950x
      uses: actions/upload-artifact@v2
      with:
        name: "s5l8950x.a"
        path: ${{ github.workspace }}/s5l8950x.a
        
    - name: rename main
      run: mv main.a ipwnder_main.a
      
    - name: upload ipwnder_main.a
      id: upload_ipwnder_main
      uses: actions/upload-artifact@v2
      with:
        name: "ipwnder_main.a"
        path: ${{ github.workspace }}/ipwnder_main.a
      
      
